apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: flaskdocker
data:
  POSTGRES_DB: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: flaskdocker
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-db-pvc
  namespace: flaskdocker
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: flaskdocker
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: flaskdocker
spec:
  ports:
    - port: 5432
      name: postgres
      protocol: TCP
  selector:
    app: postgres
