apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=postgres;"