apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: bojanpetrov/flaskdocker:latest
        ports:
        - containerPort: 4000
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DB_URL
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: POSTGRES_DB
