# postgres-secret.yaml (Secret for Postgres)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: my-app-namespace
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64 encoded 'postgres'
  POSTGRES_USER: cG9zdGdyZXM=       # base64 encoded 'postgres'
