apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # Base64 encoded value of 'postgres'
  POSTGRES_USER: cG9zdGdyZXM=  # Base64 encoded value of 'postgres'
  POSTGRES_DB: cG9zdGdyZXM=  # Base64 encoded value of 'postgres'
